name: emailService CI

on:
  pull_request:
    branches: [main, develop]
  push:
    branches: [main]

jobs:
  ci:
    uses: ./.github/workflows/email-service-base.yml
    secrets: 
      RENDER_DEPLOY_HOOK_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
    with:
      node_env: development
      script_start_service: npm run start:dev
      user_service_url: http://localhost:8089
      folder: recovery
      environment_json_file: ci.environment.json
      execute_deploy: true
