name: EmailService Base Setup

on:
  workflow_call:
    inputs:
      node_env:
        required: true
        type: string
      script_start_service:
        required: true
        type: string
      user_service_url:
        required: true
        type: string
      folder:
        required: true
        type: string
      environment_json_file:
        required: true
        type: string
    secrets:
      EMAIL_SECURITY_TEST:
        required: false

jobs:
  setup:
    environment: eventsCatalog
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: email_test
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build emailService
        run: npm run build

      - name: Checkout API tests
        uses: actions/checkout@v4
        with:
          repository: LucasMCFidelis/collectionTestApiEmailService
          path: api-tests

      - name: Checkout mock userService
        uses: actions/checkout@v4
        with:
          repository: LucasMCFidelis/collectionTestApiUserService
          path: user-mock

      - name: Run migrations
        env:
          DATABASE_URL_EMAIL: postgresql://test:test@localhost:5432/email_test
        run: npx prisma migrate deploy

      - name: Start userService mock
        run: |
          docker run -d \
            -p 8089:8080 \
            -v ${{ github.workspace }}/user-mock/postman/wiremock:/home/wiremock \
            wiremock/wiremock

      - name: Start emailService
        env:
          MOCK_USER: "true"
          MOCK_EMAIL: "true"
          DATABASE_URL_EMAIL: postgresql://test:test@localhost:5432/email_test
          USER_SERVICE_URL_DEV: ${{ inputs.user_service_url }}
          USER_SERVICE_URL_PROD: ${{ inputs.user_service_url }}
        run: |
          ${{inputs.script_start_service}} &
          sleep 5

      - name: Install Newman
        run: npm install -g newman newman-reporter-html

      - name: Run API tests
        run: |
          newman run \
            api-tests/postman/collections/36785755-3f34be95-3c4c-4660-b7cd-704cf7232a83.json \
            --folder ${{ inputs.folder }} \
            -e api-tests/postman/environments/${{ inputs.environment_json_file }} \
            --env-var "emailSecurityTest=${{ secrets.EMAIL_SECURITY_TEST }}" \
            --reporters cli,html \
            --reporter-html-export relatorio.html

      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: relatorio-newman
          path: relatorio.html
